MYSQL_HOST: 127.0.0.1
MYSQL_PORT: 3306
MYSQL_DATABASE: user
MYSQL_USER: root
MYSQL_PASSWORD: "password"
SERVER_PORT: ":8989"
MYSQL_MAXIDLE: 10
MYSQL_MAXCONN: 100
MYSQL_CONNMAXLIFETTIME: 30
MYSQL_SINGULARTABLE: true
MYSQL_LOGMODE: true